CREATE ROLE activism;
ALTER ROLE activism WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB NOLOGIN NOREPLICATION;
CREATE ROLE agl;
ALTER ROLE agl WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB NOLOGIN NOREPLICATION;
CREATE ROLE crsp_basic;
ALTER ROLE crsp_basic WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB NOLOGIN NOREPLICATION;
CREATE ROLE crsp_plus;
ALTER ROLE crsp_plus WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB NOLOGIN NOREPLICATION;
CREATE ROLE director_bio_team;
ALTER ROLE director_bio_team WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB NOLOGIN NOREPLICATION;
CREATE ROLE equilar_access;
ALTER ROLE equilar_access WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB NOLOGIN NOREPLICATION;
CREATE ROLE ipo_team;
ALTER ROLE ipo_team WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB NOLOGIN NOREPLICATION;
CREATE ROLE personality_access;
ALTER ROLE personality_access WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB NOLOGIN NOREPLICATION;


--
-- Role memberships
--

GRANT activism TO igow GRANTED BY igow;
GRANT activism TO sshin GRANTED BY igow;
GRANT agl TO igow GRANTED BY igow;
GRANT crsp_basic TO activism GRANTED BY igow;
GRANT crsp_basic TO crsp_plus GRANTED BY igow;
GRANT crsp_basic TO personality_access GRANTED BY igow;
GRANT crsp_basic TO rvijayaraghavan GRANTED BY igow;
GRANT crsp_plus TO activism GRANTED BY igow;
GRANT crsp_plus TO ipo_team GRANTED BY igow;
GRANT director_bio_team TO igow GRANTED BY igow;
GRANT equilar_access TO activism GRANTED BY igow;

